local palette = {
    grey_1 = "#000000",
    grey_2 = "#222222",
    grey_3 = "#333333",
    grey_4 = "#555555",
    neutral_1 = "#f5fccf", 
    neutral_2 = "#d8c3a9",
    neutral_3 = "#857b8a",
    neutral_4 = "#cfd2fc",
    neutral_5 = "#886666",
    cool_1 = "#a8c987",
    cool_2 = "#8fc5a9",
    cool_3 = "#87c7c9",
    warm_1 = "#e0827e",
    warm_2 = "#e0ad7e",
    warm_3 = "#e0d67e",
    bar_bg = "#7e8d8c",
    red = "#c83739",
    orange = "#c87b37",
    green = "#37c842",
    blue = "#375fc8",
    purple = "#a437c8",
    bars = "#000000",
}

local groups = {
    Normal = { fg = palette.neutral_1 },
    Identifier = { fg = palette.neutral_1 },
    Operator = { fg = palette.neutral_2 },
    Delimiter = { fg = palette.neutral_2 },
    Constant = { fg = palette.warm_2 },
    Special = { fg = palette.cool_2 },
    Keyword = { fg = palette.cool_2, italic = true },
    Statement = { fg = palette.cool_3, italic = true },
    Type = { fg = palette.cool_1, italic = true },
    String = { fg = palette.warm_1 },
    PreProc = { fg = palette.warm_1 },
    EndOfBuffer = { fg = palette.cool_3 },
    Todo = { fg = palette.solid_6, reverse = true },
    Label = { fg = palette.cool_2 },
    Comment = { fg = palette.neutral_5, italic = true },
    Error = { fg = palette.red },
    IncSearch = { reverse = true },
    TermCursor = { reverse = true },
    Title = { fg = palette.cool_3 },
    Character = { link = 'String' },
    Number = { link = 'Constant' },
    Boolean = { link = 'Constant' },
    Label = { link = 'Special' },
    Float = { link = 'Number' },
    Function = { link = 'Statement' },
    Conditional = { link = 'Statement' },
    Repeat = { link = 'Statement' },
    Include = { link = 'PreProc' },
    Define = { link = 'PreProc' },
    Macro = { link = 'PreProc' },
    PreCondit = { link = 'PreProc' },
    StorageClass = { link = 'Type' },
    Structure = { link = 'Type' },
    Typedef = { link = 'Type' },
    MatchParen = { fg = "#ffffff", bold = true },
    
    TabLineFill  = { underline = true, sp = palette.grey_4, fg = palette.neutral_1, bg = palette.grey_3, blend = 80 },
    TabLineSel   = { underline = true, sp = palette.grey_4, fg = palette.neutral_4, bg = palette.grey_3, blend = 80 },
    TabLine      = { underline = true, sp = palette.grey_4, fg = palette.neutral_1, bg = palette.grey_3, blend = 80 },
    StatusLineNC = { underline = true, sp = palette.grey_4, fg = palette.neutral_1, bg = palette.grey_3, blend = 80 },
    StatusLine   = { underline = true, sp = palette.grey_4, fg = palette.neutral_4, bg = palette.grey_3, blend = 80 },
    VertSplit    = { fg = palette.grey_4, bold = true },
    CursorLine = { sp = palette.grey_4, underdotted = true }, --{ bg = palette.grey_2 },

    ModeMsg = { bold = false },
    NonText = { fg = palette.grey_4 },

    Pmenu = { bg = palette.grey_2 }, 
    PmenuSbar = { bg = palette.red }, 
    PmenuSel = { bg = palette.red }, 

    NormalFloat = { link = "Normal" },
    FloatBorder = { link = "Normal" },
    FloatTitle = { link = 'Title' },
    FloatFooter = { link = 'Title' },
    FloatShadow = { bg = 'Black', blend=80 },
    FloatShadowThrough = { bg = 'Black', blend=100 },

    ErrorMsg = { link = "Error" },
    WinSeparator = { link = 'VertSplit' },
    WinBarNC = { link = 'WinBar' },
    DiffTextAdd = { link = 'DiffText' },
    EndOfBuffer = { link = 'NonText' },
    LineNrAbove = { link = 'LineNr' },
    LineNrBelow = { link = 'LineNr' },
    QuickFixLine = { link = 'Search' },
    CursorLineSign = { link = 'SignColumn' },
    CursorLineFold = { link = 'FoldColumn' },
    CurSearch = { link = 'Search' },
    PmenuKind = { link = 'Pmenu' },
    PmenuKindSel = { link = 'PmenuSel' },
    PmenuMatch = { link = 'Pmenu' },
    PmenuMatchSel = { link = 'PmenuSel' },
    PmenuExtra = { link = 'Pmenu' },
    PmenuExtraSel = { link = 'PmenuSel' },
    ComplMatchIns = {},
    Substitute = { link = 'Search' },
    Whitespace = { link = 'NonText' },
    MsgSeparator = { link = 'StatusLine' },
    Tag = { link = 'Special' },
    SpecialChar = { link = 'Special' },
    Delimiter = { link = 'Special' },
    SpecialComment = { link = 'Special' },
    Debug = { link = 'Special' },
    ["@markup.raw"] = { link = 'Comment' },
    ["@markup.link"] = { link = 'Identifier' },
    ["@markup.heading"] = { link = 'Title' },
    ["@markup.link.url"] = { link = 'Underlined' },
    ["@markup.underline"] = { link = 'Underlined' },
    ["@comment.todo"] = { link = 'Todo' },
    ["@comment"] = { link = 'Comment' },
    ["@punctuation"] = { link = 'Delimiter' },
    ["@constant"] = { link = 'Constant' },
    ["@constant.builtin"] = { link = 'Special' },
    ["@constant.macro"] = { link = 'Define' },
    ["@keyword.directive"] = { link = 'Define' },
    ["@string"] = { link = 'String' },
    ["@string.escape"] = { link = 'SpecialChar' },
    ["@string.special"] = { link = 'SpecialChar' },
    ["@character"] = { link = 'Character' },
    ["@character.special"] = { link = 'SpecialChar' },
    ["@number"] = { link = 'Number' },
    ["@boolean"] = { link = 'Boolean' },
    ["@number.float"] = { link = 'Float' },
    ["@function"] = { link = 'Function' },
    ["@function.builtin"] = { link = 'Special' },
    ["@function.macro"] = { link = 'Macro' },
    ["@function.method"] = { link = 'Function' },
    ["@variable.parameter"] = { link = 'Identifier' },
    ["@variable.parameter.builtin"] = { link = 'Special' },
    ["@variable.member"] = { link = 'Identifier' },
    ["@property"] = { link = 'Identifier' },
    ["@attribute"] = { link = 'Macro' },
    ["@attribute.builtin"] = { link = 'Special' },
    ["@constructor"] = { link = 'Special' },
    ["@keyword.conditional"] = { link = 'Conditional' },
    ["@keyword.repeat"] = { link = 'Repeat' },
    ["@keyword.type"] = { link = 'Structure' },
    ["@label"] = { link = 'Label' },
    ["@operator"] = { link = 'Operator' },
    ["@keyword"] = { link = 'Keyword' },
    ["@keyword.exception"] = { link = 'Exception' },
    ["@variable"] = { link = 'Identifier' },
    ["@type"] = { link = 'Type' },
    ["@type.definition"] = { link = 'Typedef' },
    ["@module"] = { link = 'Identifier' },
    ["@keyword.import"] = { link = 'Include' },
    ["@keyword.directive"] = { link = 'PreProc' },
    ["@keyword.debug"] = { link = 'Debug' },
    ["@tag"] = { link = 'Tag' },
    ["@tag.builtin"] = { link = 'Special' },
}

vim.cmd.hi("clear")
vim.cmd.colorscheme("slate")

--vim.g.colors_name = "blahblahblah"
vim.o.termguicolors = true 

for group, settings in pairs(groups) do
    settings.force = true
    vim.api.nvim_set_hl(0, group, settings)
end

